### ISSUE TITLE
New File overrides currently open file

### ISSUE THREAD

**Issue by jmjr** [lainsce/quilter#122]
The problem is:
When I'm finished writing a document and want to start a new document by clicking "New file" the first document gets overwritten automatically with the text I write in the new document.

So, as far as I can tell, there is no way to start a new file from inside the program when another file is already opened.

Quilter Version 1.4.5
OS: elementary Loki 0.4.1

**Comment by lainsce** [comment]
You have an outdated version of Quilter, the latest is 1.4.8. Try updating to the newest version and see if the bug persists, if not, I'll see what I can do.

**Comment by jmjr** [comment]
Sorry, I was wrong. I already had version 1.4.8. 

Please let me know what you need to know.

**Comment by lainsce** [comment]
There's no need for extra input, I already know what's going wrong here and I aim to fix it soon. 😄

**Comment by cassidyjames** [comment]
Just hit this and lost some pretty critical work from a meeting yesterday :cry:

**Comment by lainsce** [comment]
Oh no. I'm still trying to fix this, with GLib's "Can't close a file and open another" limitation, it's proving difficult.

**Comment by lainsce** [comment]
Wow, I actually didn't know I had it semi-coded. This New File button was more like a Purge File button. All fixed now in master. 🎉

**Comment by jmjr** [comment]
I updated to 1.5.2 but the issue still exists:

1. write something
2. click "New file"
3. click "Save" OR "Cancel"
4. Nothing is saved, all is gone

I'd really like to use Quilter but in this state of dev it's just not usable.

**Comment by lainsce** [comment]
I will see what's happening with it. Telling me "in this state of dev it's just not usable." isn't helpful, since I always read and fix every issue.
