### ISSUE TITLE
Regarding the Possible Adjustment of Text Size When Typing

### ISSUE THREAD

**Issue by axionbuster** [lainsce/quilter#163]
Hi Mr. Lainsce,

I'm a delighted user of your application. I am having trouble with the size of the text on the typing window. It is too small for my screen (which is moderately HiDPI, in fact) and needs adjustment. I need to have the option to adjust it.

I notice that you have turned down similar requests a couple times because you found it clashing with your design principle. However, I feel that, by you having features addressing the **layout** of typography (for example, the "margin" and the "spacing" and the "typographic scrolling" features, which are all great), there is little justification (as to its consistency) of your rejection regarding the **adjustment** of typography.

As you seem concerned with typography much - and the desire to perfecting it - I may suggest that you give it a second look when it comes to also ensuring harmony of your design as a thoughtful implementation of your philosophy.

Best,
@axionbuster

**Comment by lainsce** [comment]
Sorry for not seeing this issue earlier.

Which version are you currently on?

**Comment by axionbuster** [comment]
Sorry, but I have deleted the program days ago.

I was using the latest version available on the store when I first posted the comment.

**Comment by lainsce** [comment]
I can help you with it, I just need to know if you're okay with some preset sizes? :smile:

**Comment by axionbuster** [comment]
Yes, I'll be welcome with _any_ solution that supports _some_ sort of a variable text size.

Another solution could be inspecting the resolution of the screen using measures such as dots per inch and automatically recommending (or, if you would, _affix_) a suitable text size.

**Comment by lainsce** [comment]
It is fixed in master, going to release in 1.6.1, at this Friday.

**Comment by cicindel** [comment]
Hi Lainsce,
I still have this issue (elementaryOS Loki, Quilter v1.6.3) - my netbook has HD screen (1366 x 768) on 11.6" display and the font in editing mode is very tiny compared to any of the three fonts in preview mode. See for yourself:

![snimek z 2018-09-05 12-44-50](https://user-images.githubusercontent.com/19331850/45088519-82ad0800-b109-11e8-8d1a-155e1fa6ac1b.png) 
![snimek z 2018-09-05 12-45-27](https://user-images.githubusercontent.com/19331850/45088556-a2443080-b109-11e8-9c25-934ed329c3b7.png)

It would be cool if you could increase the font size a little bit or give us some option to do it ourselves (small/medium/large, similar to margin & spacing settings would be enough).

Regardless, thanks for this app, it's awesome :)

**Comment by lainsce** [comment]
What does the settings show for you in the first page?

**Comment by cicindel** [comment]
There is no option for text size in settings:
![snimek z 2018-09-06 14-34-50](https://user-images.githubusercontent.com/19331850/45157836-8496ca00-b1e2-11e8-9568-309b2657e4a5.png)
And `apt policy com.github.lainsce.quilter` gives:
```
com.github.lainsce.quilter:
  Instalovaná verze: 1.6.3
  Kandidát:          1.6.3
  Tabulka verzí:
 *** 1.6.3 500
        500 http://packages.elementary.io/appcenter xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.6.2 500
        500 http://packages.elementary.io/appcenter xenial/main amd64 Packages
     1.5.6 500
... (the list goes on like this)
```

**Comment by lainsce** [comment]
Ah yes. The text sizing setting is now only on Juno releases, sorry. It needs a newer GTK thing to operate without bugs.

**Comment by cicindel** [comment]
oh i see, okay, thanks
