### ISSUE TITLE
Selecting word count switches to character count

### ISSUE THREAD

**Issue by phase1geo** [lainsce/quilter#176]
Version: 1.6.6

I attempted to select the word count menu option in the lower left which initially works; however, as I start typing, it automatically switches to character count and displays that value instead.

**Comment by lainsce** [comment]
I'll see what I can do. (Busy until 02.10.2018)

**Comment by lainsce** [comment]
Fixed in master.

**Comment by rugglcon** [comment]
I'm still getting this bug, I have version 1.6.6 installed on elementary OS 5.0. When do you think this fix will be released?

**Comment by lainsce** [comment]
It's going to be released soon. :smile:

**Comment by rugglcon** [comment]
😍

**Comment by rugglcon** [comment]
No problem, you're only one person. Let me know if you need any help, I don't have much experience in Vala but I'm very familiar with C# and pretty familiar with GTK development in Python.

**Comment by lainsce** [comment]
I believe I can handle this, but if you wanna help, hit me at @lainsce in Telegram. :hugs:
