### ISSUE TITLE
One file can be opened many times

### ISSUE THREAD

**Issue by flaminestone** [lainsce/quilter#217]
One file can be opened many times, and link to it will be added to sidebar again. At now, no way to close only one file from sidebar, and this case add more problems with work.
* Open quilter, and open first file by "open" button
* Open first file again by "open" button

![gifout](https://user-images.githubusercontent.com/6047261/53167160-3c306480-35e8-11e9-87f2-39136e6adff7.gif)

Version: 1.7.0
Elementary OS Juno 5.0
Thanks!

**Comment by lainsce** [comment]
I'll fix this!

**Comment by lainsce** [comment]
Fixed in master, release next week.

**Comment by janxkoci** [comment]
I still see duplicate entries in sidebar for file I have open. Just updated today to 1.7.4.

**Comment by lainsce** [comment]
That's due to old state of the app. If you close them and re-open you won't see any duplicates.

**Comment by sempasha** [comment]
![Screenshot from 2019-03-20 12-44-23](https://user-images.githubusercontent.com/1610465/54667492-4d4c9280-4b0e-11e9-8ea2-640d23dd1fbd.png)

Quilter version: 1.8.0
