### ISSUE TITLE
Autosave doesn't work

### ISSUE THREAD

**Issue by png2378** [lainsce/quilter#46]
If I make changes in the file and close app window, changes should be saved automatically, right? But it's don't work.

**Comment by lainsce** [comment]
Which version are you on?
Please check it and tell me so I can know about this in detail.

**Comment by png2378** [comment]
I have latest 1.2.2 version. The problem still remains.

**Comment by lainsce** [comment]
I’ll look into it, and release a fix.

**Comment by lainsce** [comment]
Does 1.2.3 fix the bug for you?

**Comment by png2378** [comment]
@lainsce AppCenter still contains 1.2.2 (the issue is not fixed).

**Comment by lainsce** [comment]
Please wait for the release :joy: 
I already pushed it for official testing and I'm just waiting for that.

**Comment by png2378** [comment]
I installed 1.2.3 from testing repo and issue is not fixed: https://youtu.be/xasyeiqu8IM

**Comment by lainsce** [comment]
That’s REALLY strange, to be honest with you. I tested my code here in a clean build and it works flawlessly. Can I see what’s happening if you run it via terminal?

**Comment by png2378** [comment]
This is terminal log:

```
maxim@ProBook:~/Документы$ com.github.lainsce.quilter index.md 
[INFO 20:36:32.009531] Application.vala:153: Quilter version: (null)
[INFO 20:36:32.009559] Application.vala:155: Kernel version: 4.10.0-30-generic
[WARNING 20:36:32.023930] [Gtk] Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
[WARNING 20:36:32.023989] [Gtk] Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
[WARNING 20:36:32.024043] [Gtk] Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
[WARNING 20:36:38.055235] FileUtils.vala:116: Error: Произошла ошибка при удалении файла: Каталог не пуст
[WARNING 20:36:38.055285] FileUtils.vala:128: Exception found: Произошла ошибка при открытии файла «/home/maxim/Документы»: Файл существует
```

`~/.cache/com.github.lainsce.quilter` is here.

Why do we speak in a closed thread? Is this a minor issue for you?

**Comment by lainsce** [comment]
It's not a mionr issue, but it's fixed. :joy:  I dunno what happened, do you have the folder in `~/.cache`? :slightly_smiling_face:

**Comment by lainsce** [comment]
I guess this is an unsolvable issue then. :cry:

**Comment by Djaler** [comment]
I can confirm it with 1.2.4 version (from the appcenter repo)

**Comment by png2378** [comment]
@lainsce did you tried to repeat all steps from [video](https://youtu.be/xasyeiqu8IM)?

**Comment by lainsce** [comment]
I did, and on my console it doesn't show the output you have.
Also I think it's a non-bug from the looks of it, since nothing gets corrupted or damaged.

**Comment by alons45** [comment]
I lost my work twice in this app :cry: , uninstalled. @lainsce better test please, this application costs two dollars.

**Comment by lainsce** [comment]
I’m really sorry, but I don’t know what is going on, I’ve tested it on all ways, no file, with file, save with file open, save with saved file, etc, I don’t know what is needed... 😞 

Also, it doesn’t cost two dollars, you can pay two dollars, but it’s not necessary. You’d pay if you want.

**Comment by WebShapedBiz** [comment]
Can confirm same issue with version 1.2.5.

**Comment by lainsce** [comment]
As always, I'm still not sure what is happening for you guys. I've tested the app in lots of ways, and never encountered this behavior. Sorry for file corruptions, I'm still looking on how to fix this.

**Comment by WebShapedBiz** [comment]
Thank you Lains.

**Comment by ayoisaiah** [comment]
@lainsce I think you should add the option to manually save for those who don't want auto save. Also, it would be good if you insist that the user save a new file (or discard its contents) before the app is closed.

**Comment by lainsce** [comment]
The thing is, all elementary type programs only do auto-save, they never by default do a save button.
I could add the save on close dialog though, that might help people. 😄

**Comment by lainsce** [comment]
Fixed in 1.2.6 finally!

**Comment by png2378** [comment]
Please, don't close the report without a reason. This bug still not fixed!

Save button as well doesn't work. Terminal log:
```
[INFO 16:44:00.362005] Application.vala:153: Quilter version: (null)
[INFO 16:44:00.362037] Application.vala:155: Kernel version: 4.10.0-33-generic
[FATAL 16:44:03.025540] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
```

**Comment by lainsce** [comment]
OK, I tried everything I could, @png2378 .
I still don not know what is happening that it doesn't work for you, since many users didn't open duplicate issues to this one. I think there's a unseen problem that is not related with Quilter happening here, that only happens in your machine.

In all facets of the issue, this is fixed. Only on your PC it doesn't seem to work.

**Comment by png2378** [comment]
Unfortunately I can not tell you what the problem is. But it is not "my PC problem", other users confirmed the problem ITT.

**Comment by lainsce** [comment]
The other users in this thread didn't follow up with more comments so I assumed that for them, the bug is fixed.

**Comment by WebShapedBiz** [comment]
I'm still having this issue with version 1.2.6.

**Comment by lainsce** [comment]
The attitude I'm having is pure confusion as to what is happening. :confused: 
You guys assume I'm a top-notch Vala developer, but I'm still learning as I go with these 3 apps, go easy on me please since File I/O in it is really difficult for me to understand... :astonished: 

Just now in 1.2.7, I'm trying to fix some stuff with an expert Vala developer that has more years of Vala than me.

**Comment by WebShapedBiz** [comment]
Don't get bug reports personal, they are just the way of the community to help you and not to say you suck :-)

Keep up the good work.

Cheers.

**Comment by png2378** [comment]
Well, I checked this problem on live-session (elementaryos-0.4.1-stable.20170814.iso, no changes)... this bug still haunts me :confused:

I hope that Adam will help us with solution.

**Comment by AlonsoEnrique** [comment]
Hi @lainsce really this app needed unit tests, i'm developer and this is the best approach.

Happy coding and good luck

**Comment by lainsce** [comment]
Hi @AlonsoEnrique !
I do make tests with the app at every place that has an user interaction, don't get me wrong, I really test the app before I issue a new release. It's just that this bug is eluding me a lot, I really need to understand more about Vala's way of File I/O before really doing an "Eureka!" moment and fixing it.

**Comment by lainsce** [comment]
OK, I think what would help me a lot is a little "homework" I'm giving you guys:
Make a video, of you guys using Quilter extensively and doing everything that is possible with it, like opening from outside, saving, waiting 1:30 minutes for autosave to kick in, the usual. Deal? Deal.

**Comment by lainsce** [comment]
OK, guys, I think I fixed everything that is related with this bug in 1.2.7

Happy writing!

**Comment by WebShapedBiz** [comment]
Thank you Lains :+1:
