### ISSUE TITLE
Can't open from Files context menu

### ISSUE THREAD

**Issue by Djaler** [lainsce/quilter#61]
You can see all there https://youtu.be/IVV2P0TvJAs

**Comment by lainsce** [comment]
Thanks for the video! I’ll work on it for 1.2.8

**Comment by lainsce** [comment]
I believe I fixed this now in 1.2.8, was just a fix in code logic.

**Comment by Djaler** [comment]
It still doesn't work correctly https://youtu.be/m2Irb-ef4Zg

**Comment by lainsce** [comment]
I see, I think I know what's making this happen, will fix.
